import = ["/home/pujianquan/.config/alacritty/themes/themes/wombat.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Underline"

[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
x = 1
y = 2

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[window]
decorations = "none"
opacity = 0.8

[window.padding]
x = 20
y = 20
