cmds = [
  # tauri安装前提
  "paru -S webkit2gtk base-devel curl wget file openssl appmenu-gtk-module gtk3 libappindicator-gtk3 librsvg",
  "rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android",
  "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/probe-rs/probe-rs/releases/latest/download/probe-rs-toolsinstaller.sh | sh", # https://probe.rs/
  "cargo install cargo-deny",
  "cargo install cargo-generate",
  "cargo install cargo-modules",
  "cargo install cargo-tauri",
  "cargo install cargo-tarpaulin",
  "cargo install create-tauri-app",
  "cargo install crm",
  "cargo install cross",
  "cargo install kondo",
  "cargo install ldproxy",
  "cargo install mdcat",
  "cargo install navi",
  "cargo install toipe",
  "cargo install tokei",
  "cargo install trunk",
  "cargo install tauri-cli",
  "cargo install cargo-espflash",
  "cargo install cargo-espmonitor",
  "cargo install espflash",
  "cargo install espmonitor",
  "cargo install rumqttd",
  "cargo install fnm",
  "cargo install devserver",
  "cargo install trunk",
  "cargo install wokwi-server",
]
